### ISSUE TITLE
Please update frontend documentation

### ISSUE THREAD

**Issue by AL1L** [odoo/documentation#3494]
For Odoo 16, much of the frontend documentation is lacking or flat out wrong. Specifically I need these pages updated

- developer/reference/frontend/owl_components.rst
  - This one not so much because at least the documentation on Owl repo is up to date.
- developer/reference/frontend/javascript_reference.rst
- developer/reference/frontend/javascript_cheatsheet.rst

It's a pain to have to reverse engineer how things are done elsewhere, and I just have to guess if something changed from previous versions. It should be policy at Odoo that if you change the API, you change the documentation to match.

**Comment by bouvyd** [comment]
Hi

We are aware of documentation staleness, but clearly we prefer allocating resources to new features rather than documentation updates

This does not means the doc updates will not come (they will), but we plainly disagree on this
> It should be policy at Odoo that if you change the API, you change the documentation to match

I will not promise anything (as I'm not the one who decides what documentation gets done, it's usually the technical leader of the team who does that), and this issue has been seen by the people concerned.

Closing this since there is little chance this will get referenced when done. Another maintainer is free to re-open if need-be.

**Comment by AL1L** [comment]
> we prefer allocating resources to new features rather than documentation updates
bad
