### ISSUE TITLE
[16.0] OWL Frontend documentation

### ISSUE THREAD

**Issue by Heshmatkhah** [odoo/documentation#5554]
Hi
Is there any documentation for how to customize Odoo Forntend using OWL?
I found OWL documentation for customizing the backend, but how I can use them in the frontend is unclear.

**Comment by sdegueldre** [comment]
What kinds of customizations in particular are you refering to? Most of the frontend HTML is rendered on the server, and as such it should be customized on the python side, the few things that use owl in the frontend are things that appear after user interactions such as dialogs and notifications using the same dialog service and notification service as in the webclient, to customize those you should just use the same methods as for the backend.

Owl being one of our core libraries, it is *available* in the frontend, and you can create owl Apps there, for example if you wanted to create a widget with rich user interactions in the portal, but since we don't do that at the moment, there is no infrastructure code in place on our end to do that. If you'd like to write your own code to do that, I can refer you to [this experimental commit](https://github.com/odoo-dev/odoo/commit/6084de3c908cc6ddffaedaa6dbc499d0e2de1ee8) that creates a service that will spawn owl apps in much the same way as we spawn "public widgets" currently, but I think this need is niche enough at the moment that it doesn't warrant an entry in the documentation.

**Comment by Heshmatkhah** [comment]
Hi
Thanks for your reply.
I want to show a calendar similar to the odoo internal calendar (`calendar.event.calendar`) to some portal users.
I fund  [`CalendarRenderer`](https://github.com/odoo/odoo/blob/16.0/addons/web/static/src/views/calendar/calendar_renderer.js), but I really get confused about how to use it.
I prefer to create a snippet for it, but there is no documentation about writing js files of the snippet (`000.js`) in order to load data, Also, I can't make the options to work.

**Comment by sdegueldre** [comment]
Rendering a view in the frontend is a very advanced customization which explains why there is no documentation for it. You may want to look at the assets bundle `mrp_subcontracting.webclient` and how/where it's used as an example where we render a full view in the portal, but this is definitely outside the scope of what should be in the documentation in my opinion.

As far as fetching data within snippets, you can just make RPCs within their willStart method, which is [documented here](https://www.odoo.com/documentation/master/developer/reference/frontend/javascript_reference.html#Widget.willStart), there are some examples such as `s_dynamic_snippet_products` that use this strategy within a snippet.
