### ISSUE TITLE
V17 Problem with JavaScript

### ISSUE THREAD

**Issue by tecnoserviciosartavia** [odoo/documentation#8789]
I have this problem when i try to start odoo after install my module

![image](https://github.com/odoo/odoo/assets/72755012/45989e50-9dcc-43be-a2a1-8c86eb8679c3)

**Comment by CreatorRoad** [comment]
HI @tecnoserviciosartavia 

the issue occurs because. Of manifest asset load.  in odoo17 the js file is called on the specified assets. in your custom module the js has been extended in a file and it need to be called in the right asset bundle or else the issue occurs like this for fix this ----------example:

consider the dropdown js in Odoo - "import {Dropdown} from "@web/core/dropdown/dropdown";"
we extend this js file for a functionality. all the js file will segregate and stored in a bundle. so, the file needs to be load in the correct asset, for the above js, its need load in the manifest in the right assets bundle for this" 'website.assets_editor': [''navbar_color/static/src/js/dropdown.js',']" I load in the aforementioned assets bundle...

**Comment by AntoineVDV** [comment]
This one is for you @odoo/javascript-doc-review ;)

**Comment by sdegueldre** [comment]
The original issue is a problem with custom code so I think it's out of scope. The error you get in about as clear as it can be: your custom module depends on modules that don't exist. These modules have been deleted from standard Odoo which means the custom module needs to be rewritten, contact the developer of the custom code for support.

The secondary issues that are raised are lacking detail and I suggest you open a new issue with a more complete description. The documentation page for the javascript modules inside of Odoo is not *quite* up to date, though most things that it mentions still hold true. The "web.ajax" module no longer exists and so the example will not work as-is, you need to import a module that exists, eg "@web/core/assets". Though if you're just importing a module blindly without knowing what you want to use it for it's unlikely to help you. I'd suggest you start with the JavaScript tutorials in the documentation and come back to the JS modules page with that understanding under your belt. The tutorials are much more up to date.

We will be updating this page of the documentation some time soon, we have a task internally for this.
